---
title: Python and R
author: ''
date: '2020-12-11'
slug: python-and-r
categories: []
tags: []
description: ''
---

# Let's talk about Pyhton and Rstudio

In the Fall of 2020, I took a course called "Computational Biology and Bioinformatics" at the University of Texas, in which I learned how to navigate Rstudio and Python programming languages. What I found super interesting about these resources is that they aren't mutually exclusive and that you can actually use them both together! The two coding projects that are located in the "Projects" tab of this website were completed solely using Rstudio; however, in this post I will show you how one can pull a file from Rstudio and complete Python functions using it. To do so, I will be using a dataset called `quakes` which is one that I became very familar with throughout the course. 

```{r}
library(reticulate)
quakes_blog <- quakes
hist(quakes$lat)
#the above code is all in Rstudio
```

Now I'm going to use the same `quakes` dataset from Rstudio to run some example python codes for y'all. To access R defined objects, I have to include `r.` within my code (as you can see below).
```{python}
r.quakes_blog.mag.mean()
```

