<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Melanie Albrecht (she/her)" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>FINALPROECT2</title>
    <meta name="generator" content="Hugo 0.79.0" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">FINALPROECT2</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         November 19, 2020 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="introduction" class="section level2">
<h2>Introduction</h2>
<pre class="r"><code>Bird_Nest &lt;- read_csv(&quot;BirdNest.csv&quot;)
Bird_Nest &lt;- Bird_Nest %&gt;% select(- X1, - Page, - Species, - Nestling, - Incubate)
Bird_Nest &lt;- Bird_Nest %&gt;% na.omit()
Bird_Nest &lt;- Bird_Nest[-c(11, 12, 29, 30, 21, 28),] #these rows had errors with the data (didn&#39;t match the format)
Bird_Nest &lt;- Bird_Nest%&gt;%mutate(Color_cat = case_when(Color==1 ~ &quot;Yes&quot;, Color==0 ~ &quot;No&quot;))
#The above code were lines I ran to set up my dataset</code></pre>
<p>Throughout this semester, I have been enrolled in a course called &quot;Animal Behavior,&quot; and we have spent a lot of time discussing various species of birds as well as their behaviors (primarily those related to parental care). With that being said, I decided to choose the dataset <code>Bird_Nest</code> because it contains information regarding species and nest characteristics for many birds from North America. All of the data came from a project that a student from Grinnell College completed in 1999, using information from a book called, &quot;The Birders Handbook (1998).&quot; For the purpose of this project, I chose to eliminate certain variables that I deemed unnecessary (as you can tell from the above code) and will be using the 8 variables that are listed below. There was also one observation that contained NAs in many of the columns, so I decided to remove it in its entirety (there are now 77 different birds/observations).</p>
<p><code>Common</code>- The non-latin name for the species (identifier variable)</p>
<p><code>Length</code>- The species's average body length in centimeters</p>
<p><code>Nesttype</code>- The type of nest the species occupies (cup, cavity, saucer, or crevice)</p>
<p><code>Location</code>- The location of the bird's nest (deciduous forest, bridge, shrub, ground, bank, building, coniferous forest, snag, or cliff)</p>
<p><code>No.eggs</code>- Average number of eggs in the nest</p>
<p><code>Color</code>- Solid/plain color is designated as 0 and speckled/spotted coloration is designated as 1</p>
<p><code>Color_cat</code>- This is an extra categorical variable (not include in the above count of variables) that I created, if the observation was a 1 in the numeric color variable it is designated as &quot;Yes&quot; here and if it was 0 it is catagorized as &quot;No&quot;</p>
<p><code>Totcare</code>- Total species care by parent (incubating plus nestling time)</p>
<p><code>Closed.</code>- 0 is the designation for open nest (saucer or cup) and 1 represents closed nest (cavity or crevice)</p>
</div>
<div id="manova" class="section level2">
<h2>MANOVA</h2>
<div id="manova-assumptions" class="section level3">
<h3>MANOVA Assumptions</h3>
<pre class="r"><code>library(rstatix)

nest &lt;- Bird_Nest$Nesttype 
DVs &lt;- Bird_Nest %&gt;% select(Length,No.eggs,Totcare)

#Test multivariate normality for each group (null: assumption met)
sapply(split(DVs,nest), mshapiro_test)</code></pre>
<pre><code>##           cavity     crevice    cup          saucer     
## statistic 0.8585833  0.7893586  0.6062924    0.6297763  
## p.value   0.01453665 0.08933946 1.118121e-10 0.001240726</code></pre>
<p>The results of the Shapiro test confirmed that the data is not distributed normally (all p values were less than 0.05). Thus, this test concluded that the homogeneity of covariance assumption was violated.</p>
</div>
<div id="manova-follow-up-tests" class="section level3">
<h3>MANOVA &amp; Follow-up Tests</h3>
<pre class="r"><code>man1&lt;-manova(cbind(Length, No.eggs, Totcare)~Nesttype, data=Bird_Nest)
summary(man1) #The p was significant, so now I get the univariate ANOVA</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Nesttype 3 0.32657 2.9724 9 219 0.002342 **
## Residuals 73
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>summary.aov(man1) #univarte ANOVAs from MANOVA</code></pre>
<pre><code>## Response Length :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Nesttype 3 145.81 48.602 1.8738 0.1415
## Residuals 73 1893.49 25.938
##
## Response No.eggs :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Nesttype 3 22.76 7.5868 4.6846 0.00477 **
## Residuals 73 118.23 1.6195
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Response Totcare :
## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Nesttype 3 175.35 58.449 2.7945 0.04623 *
## Residuals 73 1526.85 20.916
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>Bird_Nest%&gt;%group_by(Nesttype)%&gt;%summarize(mean(Length),mean(No.eggs),mean(Totcare)) #Eyeball the mean differences</code></pre>
<pre><code>## # A tibble: 4 x 4
##   Nesttype `mean(Length)` `mean(No.eggs)` `mean(Totcare)`
##   &lt;chr&gt;             &lt;dbl&gt;           &lt;dbl&gt;           &lt;dbl&gt;
## 1 cavity             15.6            5.41            29.5
## 2 crevice            18.2            5.17            30.2
## 3 cup                18.9            4.22            26.9
## 4 saucer             16.9            3.62            23.5</code></pre>
<pre class="r"><code>pairwise.t.test(Bird_Nest$Length, Bird_Nest$Nesttype, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  Bird_Nest$Length and Bird_Nest$Nesttype 
## 
##         cavity crevice cup  
## crevice 0.427  -       -    
## cup     0.023  0.805   -    
## saucer  0.658  0.741   0.442
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(Bird_Nest$No.eggs, Bird_Nest$Nesttype, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  Bird_Nest$No.eggs and Bird_Nest$Nesttype 
## 
##         cavity crevice cup   
## crevice 0.7593 -       -     
## cup     0.0012 0.2126  -     
## saucer  0.0137 0.1170  0.3726
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>pairwise.t.test(Bird_Nest$Totcare, Bird_Nest$Nesttype, p.adj = &quot;none&quot;)</code></pre>
<pre><code>## 
##  Pairwise comparisons using t tests with pooled SD 
## 
## data:  Bird_Nest$Totcare and Bird_Nest$Nesttype 
## 
##         cavity crevice cup  
## crevice 0.825  -       -    
## cup     0.041  0.229   -    
## saucer  0.020  0.060   0.159
## 
## P value adjustment method: none</code></pre>
<pre class="r"><code>0.05/13 #bonferroni correction</code></pre>
<pre><code>## [1] 0.003846154</code></pre>
<pre class="r"><code>1- (.95)^13 #probability of having at least 1 type 1 error</code></pre>
<pre><code>## [1] 0.4866579</code></pre>
<p>To determine the effect of the type of nest (cavity, crevice, cup, or saucer) on 3 dependent variables (body length, number of eggs, and total time of care), I ran a 1-way MANOVA. The null hypothesis was that for the 3 DVs, means for each nest type are equal, and the alternative being that means are not equal. (Refer to the previous section for discussion of MANOVA assumptions). The results on the one-way MANOVA confirmed that, for at least one of the dependent variables, there were significant differences found across the different types of nests, Pillai trace = .32 pseudo F(9, 219) = 2.9724 p &lt; 0.05.</p>
<p>After the MANOVA was significant, I needed to conduct univariate ANOVAs for each dependent variable. This time I accounted for Type 1 error rates when doing multiple comparisons, by using the bonferroni correction, which was found to be 0.0038. I found this by dividing the original alpha of 0.05 by the number of tests that were run which was 13 (1 MANOVA, 3 ANOVAs, and 9 t-tests). The probability of having at least one type I error is 0.487. Using the adjusted significance level, it was found that the univariate ANOVAs for all 3 dependent variables were insignificant, F(3, 73) = 119.26, p &gt; .0038 (for each DV). The results of the post hoc analysis also came back insignificant (fail to reject the null hypothesis) when considering the bonferroni correction. This means that none of the nest types had significantly different mean values with regards to body length, number of eggs, and total parental care. However, the original MANOVA is still significant when considering this adjustment, Pillai trace = .32 pseudo F(9, 219) = 2.9724 p &lt; 0.0038.</p>
</div>
</div>
<div id="randomization-test" class="section level2">
<h2>Randomization Test</h2>
<div id="one-way-anova" class="section level3">
<h3>One-way ANOVA</h3>
<pre class="r"><code>boxplot(No.eggs ~ Nesttype, data = Bird_Nest) #normality assumption was</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(car)
leveneTest(No.eggs ~ Nesttype, data = Bird_Nest) #equal variance assumption was met</code></pre>
<pre><code>## Levene&#39;s Test for Homogeneity of Variance (center =
median)
## Df F value Pr(&gt;F)
## group 3 0.5626 0.6414
## 73</code></pre>
<pre class="r"><code>summary(aov(No.eggs~Nesttype,data=Bird_Nest))</code></pre>
<pre><code>## Df Sum Sq Mean Sq F value Pr(&gt;F)
## Nesttype 3 22.76 7.587 4.685 0.00477 **
## Residuals 73 118.23 1.620
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>The above one-way ANOVA was ran prior to the randomization test in order to compute the observed F-statistic.</p>
</div>
<div id="the-randomization-test" class="section level3">
<h3>The Randomization Test</h3>
<pre class="r"><code>obs_F&lt;-4.685

Fs&lt;-replicate(5000,{
  new&lt;-Bird_Nest%&gt;%mutate(No.eggs=sample(No.eggs))
  SSW&lt;- new%&gt;%group_by(Nesttype)%&gt;%summarize(SSW=sum((No.eggs-mean(No.eggs))^2))%&gt;%summarize(sum(SSW))%&gt;%pull
  SSB&lt;- new%&gt;%mutate(mean=mean(No.eggs))%&gt;%group_by(Nesttype)%&gt;%mutate(groupmean=mean(No.eggs))%&gt;%summarize(SSB=sum((mean-groupmean)^2))%&gt;%summarize(sum(SSB))%&gt;%pull
  (SSB/3)/(SSW/73)
})

mean(Fs&gt;obs_F) #This is the p-value</code></pre>
<pre><code>## [1] 0.0306</code></pre>
<pre class="r"><code>hist(Fs, prob=T); abline(v = obs_F, col=&quot;red&quot;,add=T)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-5-1.png" width="768" style="display: block; margin: auto;" /> To determine the effect of the nest type on the number of eggs contained in a nest, I decided to conduct a randomization test for the F-statistic/Anova. The null hypothesis was that the mean number of eggs does not differ based on the type of nest and the alternative was that there are differences in mean egg number between the various types of nests. The histogram shows the expected distribution of F-statistics under the null hypothesis (randomization distribution). The observed F-statistic (4.685) is shown in red on the histogram. The p-value was found to be 0.0322, which is equivalent to the proportion of F-statistics in the distribution that are greater than 4.685 (observed). Since this p-value is less than 0.05, the null hypothesis is rejected and I can conclude that the mean number of eggs does differ based on the type of nest. So, although the observed F-statistic is plausible under the null distribution, it is far enough out in this distribution that we can reject the null hypothesis</p>
</div>
</div>
<div id="linear-regression-model" class="section level2">
<h2>Linear Regression Model</h2>
<pre class="r"><code>Bird_Nest$Totcare_c &lt;- Bird_Nest$Totcare - mean(Bird_Nest$Totcare)
fit_1&lt;-lm(Length ~ Color_cat*Totcare_c, data=Bird_Nest)
summary(fit_1)</code></pre>
<pre><code>##
## Call:
## lm(formula = Length ~ Color_cat * Totcare_c, data =
Bird_Nest)
##
## Residuals:
## Min 1Q Median 3Q Max
## -12.4911 -2.9744 -0.6744 2.9186 12.8132
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 18.45388 1.42738 12.929 &lt;2e-16 ***
## Color_catYes -0.36822 1.54839 -0.238 0.8127
## Totcare_c -0.07565 0.28799 -0.263 0.7935
## Color_catYes:Totcare_c 0.56060 0.31555 1.777 0.0798 .
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 4.834 on 73 degrees of freedom
## Multiple R-squared: 0.1635, Adjusted R-squared: 0.1292
## F-statistic: 4.758 on 3 and 73 DF, p-value: 0.004376</code></pre>
<p>The intercept is 18.45, which represents the predicted body length for non colored birds (solid/plain) with an average amount of total parental care. For birds with average amounts of parental care, colored birds (spotted/speckled) have a predicted body length that is 0.368cm less than non-colored birds. The estimated slope for total parental care on body length for non-colored birds is -0.076 (negative correlation). Furthermore, the slope of total parental care on body length for colored birds is 0.561 greater than for non-colored birds. The R-squared value is 0.164, which represents the proportion of variation that the model explains.</p>
<div id="plot-of-regression" class="section level3">
<h3>Plot of Regression</h3>
<pre class="r"><code>ggplot(Bird_Nest, aes(x=Totcare_c, y=Length, color=Color_cat)) + geom_point(aes(color=Color_cat)) + geom_smooth(method = &quot;lm&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-7-1.png" width="768" style="display: block; margin: auto;" /></p>
</div>
<div id="assumptions" class="section level3">
<h3>Assumptions</h3>
<pre class="r"><code>library(lmtest)
library(sandwich)
bptest(fit_1) #homoskedasticity assumption was met</code></pre>
<pre><code>## 
##  studentized Breusch-Pagan test
## 
## data:  fit_1
## BP = 6.3167, df = 3, p-value = 0.09718</code></pre>
<pre class="r"><code>resids&lt;-fit_1$residuals; fitvals&lt;-fit_1$fitted.values
ggplot()+geom_point(aes(fitvals,resids))+geom_hline(yintercept=0, col=&quot;red&quot;)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-8-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>ggplot()+geom_histogram(aes(resids),bins=10)</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-8-2.png" width="768" style="display: block; margin: auto;" /> The resulting p-value for the Breuch-Pagan test was 0.097, which is greater than 0.05, so it can be confirmed that the data meets the homoskedasticity assumption. Based on the scatterplot, one can see that the data is fairly linear, so the linearity assumption can be confirmed; however, there are some outliers which linear regressions are sensitive to. Lastly, the histogram of the residuals shows that the data looks pretty normal.</p>
</div>
<div id="w-robust-standard-errors" class="section level3">
<h3>W/ Robust Standard Errors</h3>
<pre class="r"><code>coeftest(fit_1, vcov = vcovHC(fit_1))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) 18.453883 1.148912 16.0621 &lt; 2e-16 ***
## Color_catYes -0.368219 1.318132 -0.2793 0.78077
## Totcare_c -0.075649 0.160053 -0.4726 0.63787
## Color_catYes:Totcare_c 0.560598 0.224734 2.4945 0.01488
*
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>There was only 1 significant result that was found when recomputing the regression with robust standard errors, which was a change with regards to the previous regression. That being: the slope of total parental care on body length for colored birds is 0.561 greater than for non-colored birds. This difference is in fact significant,(b= 0.561,t= 2.49, p= 0.015), even though it wasn't before.</p>
</div>
</div>
<div id="bootstrapped-ses" class="section level2">
<h2>Bootstrapped SEs</h2>
<pre class="r"><code>samp_distn&lt;-replicate(5000, {
       boot_dat &lt;- sample_frac(Bird_Nest, replace=T) 
       fit_2 &lt;- lm(Length ~ Color_cat*Totcare_c, data=boot_dat) 
       coef(fit_2)
   })

samp_distn %&gt;% t %&gt;% as.data.frame %&gt;% summarize_all(sd)</code></pre>
<pre><code>## (Intercept) Color_catYes Totcare_c
Color_catYes:Totcare_c
## 1 1.307904 1.459065 0.2808088 NA</code></pre>
<p>The bootstrapped standard errors (SEs) only vary slightly from the previous SEs that were computed. (Note that the SE for the interaction of color and total parental care is not available in this case.) When compared to the original SEs, the bootstrapped ones are slighly smaller which means there is less of a spread around the mean (example: the SE for the intercept changed from 1.427 to 1.195). When compared to the robust SEs, the bootstrapped ones are slighly larger which means there is more of a spread around the mean (example: the SE for the intercept changed from 1.149 to 1.195).</p>
</div>
<div id="logistic-regression-2-variables" class="section level2">
<h2>Logistic Regression (2 variables)</h2>
<pre class="r"><code>library(tidyverse)
library(lmtest)
library(glmnet)
library(sandwich)
fit_log &lt;- glm(Closed. ~ Length + No.eggs,data = Bird_Nest,family = binomial(link=&quot;logit&quot;))
coeftest(fit_log)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -3.629455 2.224895 -1.6313 0.10283
## Length -0.063861 0.068645 -0.9303 0.35221
## No.eggs 0.798680 0.331288 2.4108 0.01592 *
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit_log))</code></pre>
<pre><code>## (Intercept)      Length     No.eggs 
##  0.02653063  0.93813553  2.22260481</code></pre>
<p>The odds of the nest being closed is 0.027 when body length is 0 cm and the number of eggs is 0 (intercept). When controlling for the number of eggs, for every 1 cm increase in body length, the odds of the nest being closed increases by a factor of 0.938 (not significant). When controlling for body length, for every 1 unit increase in the number of eggs, the odds of the nest being closed increases by a factor of 2.22 (significant, p-value= 0.0159).</p>
<pre class="r"><code>prob &lt;- predict(fit_log, type = &quot;response&quot;)

(56+7)/77 #accuracy</code></pre>
<pre><code>## [1] 0.8181818</code></pre>
<pre class="r"><code>7/8 #specificity</code></pre>
<pre><code>## [1] 0.875</code></pre>
<pre class="r"><code>56/60 #sensitivity</code></pre>
<pre><code>## [1] 0.9333333</code></pre>
<pre class="r"><code>56/57 #precision</code></pre>
<pre><code>## [1] 0.9824561</code></pre>
<pre class="r"><code>table(predict = as.numeric(prob &gt; 0.5), truth = Bird_Nest$Closed.) %&gt;% addmargins </code></pre>
<pre><code>##        truth
## predict  0  1 Sum
##     0   56 13  69
##     1    1  7   8
##     Sum 57 20  77</code></pre>
<p>The accuracy is 0.818, which represents the proportion of correctly classified birds (closed or open nest). The sensitivity or true positive rate is the proportion of open nests (designated as 0) that were correctly classified and it is 0.812. The specificity or true negative rate is 0.875 and it represents the proportion of closed nests (designated as 1) that were correctly classified. The precision, which is the propotion of nests classified as open that actually are open, is 0.982. (Note: it would not knit the class_diag function because it said that it did not exist)</p>
<pre class="r"><code>library(plotROC)
ROC_plot &lt;- ggplot(data = Bird_Nest) + geom_roc(aes(d = Closed., m = Length + No.eggs), n.cuts = 0)
ROC_plot</code></pre>
<p><img src="../../project/project2_files/figure-html/unnamed-chunk-13-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROC_plot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.4684211</code></pre>
<p>The tradeoff between sensitivity and specificity can be visualized with the above ROC curve. The AUC value is the area under that respective curve. The computed AUC is 0.468, which is considered a very bad AUC value.</p>
</div>
<div id="logistic-regression-all-variables" class="section level2">
<h2>Logistic Regression (all variables)</h2>
<div id="classification-diagnostics" class="section level3">
<h3>Classification Diagnostics</h3>
<pre class="r"><code>library(tidyverse)
library(lmtest)

BirdNest_ALL &lt;- Bird_Nest %&gt;% select(-Color_cat, -Common, -Location) #got rid of unecessary variables and ones I accidentally made

fit_ALL &lt;- glm(Closed. ~ ., data = BirdNest_ALL, family = &quot;binomial&quot;)
prob_ALL &lt;- predict(fit_ALL, type = &quot;response&quot;)

table(predict = as.numeric(prob_ALL &gt; 0.5), truth = BirdNest_ALL$Closed.) %&gt;% addmargins</code></pre>
<pre><code>##        truth
## predict  0  1 Sum
##     0   57  0  57
##     1    0 20  20
##     Sum 57 20  77</code></pre>
<p>It would not knit because it said the class_diag function did not exist. ### LASSO</p>
<pre class="r"><code>library(glmnet)
set.seed(1234)

LASS_response &lt;- as.matrix(BirdNest_ALL$Closed.)
BNest_preds &lt;- model.matrix(Closed. ~ ., data = BirdNest_ALL)[, -1]
BNest_preds &lt;- scale(BNest_preds)
cv &lt;- cv.glmnet(BNest_preds, LASS_response, family = &quot;binomial&quot;)
lasso_fit &lt;- glmnet(BNest_preds, LASS_response, family = &quot;binomial&quot;, lambda = cv$lambda.1se)
coef(lasso_fit)</code></pre>
<pre><code>## 9 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                        s0
## (Intercept)     -4.214242
## Length           .       
## Nesttypecrevice  .       
## Nesttypecup     -7.038323
## Nesttypesaucer  -2.959390
## No.eggs          .       
## Color            .       
## Totcare          .       
## Totcare_c        .</code></pre>
<p>As determined by the LASSO, the variables <code>Nesttypecup</code> and <code>Nesttypesaucer</code> will be retained because they are the most predictive variables.</p>
<p>The rest would not knit because it said the class_diag function did not exist.</p>
</div>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
